export const sorts = [
  {
    title: "background",
    items: [
      "wave",
      "moonlight",
      "space",
      "city",
      "paradise",
      "cyan",
      "orange",
      "blue",
      "pink",
      "green",
    ],
  },
  {
    title: "body",
    items: [
      "Golden Bill Bright ",
      "Golden Foxy",
      "Golden Bill ",
      "Zombie ",
      "Shiba ",
      "Foxy ",
      "Bill ",
      "Harry ",
      "Lan ",
      "Kilu ",
    ],
  },
  {
    title: "mouth",
    items: ["Smile", "Sad", "Bottom teeth", "Teeth"],
  },
  {
    title: "eyes",
    items: [
      "Laser Beam",
      "Rinnegan",
      "Asta",
      "Zombie",
      "Ruby",
      "Diamond",
      "Relax Diamond",
      "Corrupted",
      "Thor God",
      "Pure Eye",
      "Demon",
      "Angry",
      "Rebecca",
      "Ban",
      "Senin",
      "Instinct",
      "confuse",
      "Simple",
      "Amazed",
      "Heterochromia",
      "Cute",
      "Relax Heterochromia",
      "Open",
      "Relax",
      "Eyes Naughty",
    ],
  },
  {
    title: "eyewear",
    items: [
      "Special Gas Mask",
      "SnowBoard Rainbow",
      "Gas Mask",
      "Monocle",
      "Cyborg",
      "Meter",
      "3D Glasses",
      "Harry",
      "SnowBoard Blue",
      "Sun Glasses",
      "Yellow Glasses",
      "Red Glasses",
    ],
  },
  {
    title: "clothes",
    items: [
      "Coat",
      "Coat Red",
      "Suit",
      "Sweater Blue",
      "Sweater",
      "Jacket Red",
    ],
  },
  {
    title: "headwear",
    items: [
      "Helmet",
      "Ranger White",
      "Chop",
      "Assassin mask",
      "Ranger Red",
      "Egyptian Hat",
      "Crown",
      "Ear Cuff",
      "Hat Glasses",
      "Fire Gem",
      "BTC Beanie",
      "Tiara",
      "Pepe Hat",
      "Miner Helmet",
      "Frog Hat",
      "Plunge",
      "Beanie",
      "Pirate's Hat",
      "CowBoy Hat",
      "Bushido",
      "Night Cap",
      "Karate Bandana",
      "MC Cap",
      "Ninja Bandana",
      "Yellow Cap",
      "Tai",
      "Red Cap",
      "Baseball Cap",
    ],
  },
  {
    title: "earing",
    items: ["Gold", "Silver"],
  },
  {
    title: "unique fox",
    items: ["Mecha Fox", "Ghost Fox", "Electro", "Storm", "Plant Fox"],
  },
  {
    title: "Attributes",
    items: ["1", "4", "5", "6", "7", "8"],
  },
];
